### ISSUE TITLE
How to extract contents of a TCP stream like "-e" parameter of tcptrace?

### ISSUE THREAD

**Issue by FinalTheory** [hgn/captcp#31]
I've read the doc again and again but found nothing. Then I looked into the source code and seems that this feature is not provided?

**Comment by hgn** [comment]
Hey @FinalTheory,

sorry but this feature is currently not supported. It should be a matter of some additional lines but I currently prefer __not__ add this options. captcp is for **metadata** extraction and the like - not to analyse nor extract payload data. Sounds valid?

**Comment by FinalTheory** [comment]
Thanks for your reply
